### ISSUE TITLE
STAR_2.4.0f1 does not compile on Linux (Fedora 18) g++ 4.8.3

### ISSUE THREAD

**Issue by gnewton** [alexdobin/STAR#6]
$ make STAR
g++ -c -O3 -pipe -std=c++0x -Wall -Wextra -fopenmp -D'COMPILATION_TIME_PLACE="Fri Nov 14 17:58:46 EST 2014 :/home/newtong/Downloads/STAR-STAR_2.4.0f1/source"'   Parameters.cpp
Parameters.cpp: In member function ‘void Parameters::inputParameters(int, char*_)’:
Parameters.cpp:209:37: error: ‘parametersDefault’ was not declared in this scope
     string parString( (const char_) parametersDefault,parametersDefault_len);
                                     ^
Parameters.cpp:209:55: error: ‘parametersDefault_len’ was not declared in this scope
     string parString( (const char_) parametersDefault,parametersDefault_len);
                                                       ^
Parameters.cpp:697:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int ii=0;ii<vAttr1.size();ii++) {
                                  ^
make: *_\* [Parameters.o] Error 1
$

$ g++ -v
Target: x86_64-unknown-linux-gnu
gcc version 4.8.3 (GCC) 

On Fedora 18
$ uname -a
Linux onottr624241 3.11.10-100.fc18.x86_64 #1 SMP Mon Dec 2 20:28:38 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
$

**Comment by lgautier** [comment]
Or on debian xxd appears bundled with `vim-common`.
